### ISSUE TITLE
Compilation errors when installing in sl-release-6.6-1.x86_64

### ISSUE THREAD

**Issue by thedaniel** [atom/scrollbar-style#10]
_From @acampove on October 24, 2015 13:19_

Hi,

When following https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md for fedora/centos/Rhel I get a lot of error messages when running script/build. I am told at the end of the message that:

npm ERR! Please include the following file with any support request:
npm ERR!     /home/acampove/Downloads/atom/npm-debug.log

I cant attach the file for some reason, but the lines at the end say:

10864 error node v0.10.40
10865 error npm  v2.13.3
10866 error code ELIFECYCLE
10867 error scrollbar-style@3.2.0 install: `node-gyp rebuild`
10867 error Exit status 1
10868 error Failed at the scrollbar-style@3.2.0 install script 'node-gyp rebuild'.
10868 error This is most likely a problem with the scrollbar-style package,
10868 error not with npm itself.
10868 error Tell the author that this fails on your system:
10868 error     node-gyp rebuild
10868 error You can get their info via:
10868 error     npm owner ls scrollbar-style
10868 error There is likely additional logging output above.
10869 verbose exit [ 1, true ]

Any idea what might be the problem?

Thanks.

_Copied from original issue: atom/atom#9275_

**Comment by sadick254** [comment]
This should now be fixed with the new N-API migration. I will go ahead and close this one out. In case you still experience failures let me know. I am happy to reopen the issue. 😁
